### ISSUE TITLE
Firehose: gRPC Endpoint details

### ISSUE THREAD

**Issue by jubeless** [streamingfast/firehose#13]
We need a page to explain the steps and what to expect from the firehose/substreams gRPC output. How they relate to different chain's websockets and/or polling mechanisms.

Context is someone asking:

"What's the difference between RPC calls eth_newHeads + eth_getBlockByNumber and Firehose push mechanic mentioned here https://thegraph.com/blog/substreams-parallel-processing"

https://discord.com/channels/666749063386890256/820011680842907761/996409023425421423

**Comment by seanmooretechwriter** [comment]
Need additional information and help from the dev team to resolve this.

**Comment by AmineAfia** [comment]
any updates on this?
