### ISSUE TITLE
Upon connect, send the trace_id

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/firehose#21]
For easier debugging purposes if would be great if we could connect a client's session information with what is going on in the backend.  Backend keeps information based on the trace_id.  However, if there is no error, the client never knows its trace id.

On connect, firehose should send a meta-data message including the trace_id before sending any of the requested blocks.
graph_node could keep track of this information.

**Comment by maoueh** [comment]
@sduchesneau
