### ISSUE TITLE
Migrate Firehose Doc to Gitbook

### ISSUE THREAD

**Issue by jubeless** [streamingfast/firehose#5]
Move firehose.streamingfast.io to GitBooks, following a similar pattern we have done for Substreams

**Comment by seanmooretechwriter** [comment]
The docs are all ported at this point and have been. There is a new structure to the docs and content as well.

**Comment by seanmooretechwriter** [comment]
I'm going to close this per the Zoom conversation with Julien on 09/06/22. The overall work for this is done and smaller, more granular tasks have been identified and will be input into Planning.
