### ISSUE TITLE
Firehose: Revist doc layout and architecture

### ISSUE THREAD

**Issue by jubeless** [streamingfast/firehose#6]
The info in here: https://github.com/streamingfast/sf-ethereum duplicates some installation instructions for the Ethereum stack, which will probably be better living in the firehose.streamingfast.io docs, in the Ethereum section (in an admin guide?). Let's think of what should go there, and what should point to what, so we don't duplicate, and have more context and links in the docs.
The https://firehose.streamingfast.io/operate/reference/ section also have some specifics for each protocols, perhaps we should have a higher-level separation of protocols, with a child page listing flags for running the firehose. And perhaps some "common flags" section somewhere else.

**Comment by seanmooretechwriter** [comment]
I'm marking this completed for now. There are new tasks that encompass what is here now split into more granularity.
